name: CI Workflow

on:
  push:
  pull_request:

jobs:
  build_conda_packages:

  
    name: Build conda packages
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: nvcr.io/nvidia/l4t-jetpack:r35.3.1
          options: -v ${{ github.workspace }}:/work
          run: |
            ## Install miniforge3
            apt -y update
            apt -y install curl git
            curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
            export CONDA_PREFIX=/root/miniforge3
            bash Miniforge3-$(uname)-$(uname -m).sh -b -p $CONDA_PREFIX
            $CONDA_PREFIX/condabin/mamba install -y -n base conda-build anaconda-client conda-forge-pinning
            # Workaround for https://github.com/conda/conda-build/issues/4984
            $CONDA_PREFIX/condabin/mamba update -y -n base --all
            ### Build nvmpi
            cd /work
            $CONDA_PREFIX/condabin/conda run -n base conda build -m ${CONDA_PREFIX}/conda_build_config.yaml -c conda-forge nvmpi
            ### Build ffmpeg with nvmpi patch
            git clone -b jetson-ffmpeg https://github.dev/ami-iit/ffmpeg-feedstock
            git clone https://github.com/madsciencetist/jetson-ffmpeg
            cd jetson-ffmpeg
            # Make sure that this sha is coherent with the one used in nvmpi/meta.yaml
            git checkout 4a33a2cca94970c92340191cdcc016a1636e39ad
            cd ..
            cp ./jetson-ffmpeg/ffmpeg_patches/ffmpeg6.0_nvmpi.patch ./ffmpeg-feedstock/recipe/patches
            # Build ffmpeg gpl variant
            $CONDA_PREFIX/condabin/conda run -n base conda build -m ./ffmpeg-feedstock/.ci_support/linux_aarch64_license_familygpl.yaml -c conda-forge -c local ./ffmpeg-feedstock/recipe
            # Build ffmpeg lgpl variant
            $CONDA_PREFIX/condabin/conda run -n base conda build -m ./ffmpeg-feedstock/.ci_support/linux_aarch64_license_familylgpl.yaml -c conda-forge -c local ./ffmpeg-feedstock/recipe

