name: CI Workflow

on:
  push:
  pull_request:

jobs:
  build_conda_packages:

  
    name: Build conda packages
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: nvcr.io/nvidia/l4t-base:r35.1.0
          options: -v ${{ github.workspace }}:/work
          run: |
            apt -y update
            apt -y install curl
            curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
            export CONDA_PREFIX=/root/miniforge3
            bash Miniforge3-$(uname)-$(uname -m).sh -b -p $CONDA_PREFIX
            $CONDA_PREFIX/condabin/mamba install -y -n base conda-build anaconda-client conda-forge-pinning
            # Workaround for https://github.com/conda/conda-build/issues/4984
            $CONDA_PREFIX/condabin/mamba update -y -n base --all
            cd /work
            $CONDA_PREFIX/condabin/conda run -n base conda build -m ${CONDA_PREFIX}/conda_build_config.yaml -c conda-forge nvmpi

            
